catalogMode: prefer

shellEmulator: true

trustPolicy: no-downgrade
packages:
  - playground

overrides:
  global-agent: ^4.1.2
catalog:
  '@mdream/crawl': ^0.16.0
  '@types/semver': ^7.7.1
  bumpp: ^10.4.1
  giget: ^3.1.2
  mdream: ^0.16.0
  ofetch: ^1.5.1
  pathe: ^2.0.3
  semver: ^7.7.4
  std-env: ^3.10.0
  tsx: ^4.21.0
  unagent: ^0.0.8

catalogs:
  deps:
    '@clack/prompts': ^1.0.1
    '@huggingface/transformers': ^3.8.1
    citty: ^0.2.1
    consola: ^3.4.2
    log-update: ^7.2.0
    mdast-util-from-markdown: ^2.0.3
    mdast-util-frontmatter: ^2.0.1
    mdast-util-to-string: ^4.0.0
    micromark-extension-frontmatter: ^2.0.0
    mlly: ^1.8.0
    oxc-parser: ^0.116.0
    p-limit: ^7.3.0
    retriv: ^0.10.3
    sqlite-vec: ^0.1.7-alpha.10
    tinyglobby: ^0.2.15
    typescript: 6.0.0-beta
    unist-util-visit: ^5.1.0
  dev-build:
    '@types/node': ^25.3.3
    obuild: ^0.4.31
  dev-lint:
    '@antfu/eslint-config': ^7.6.1
  dev-test:
    '@vitest/coverage-v8': ^4.0.18
    evalite: ^0.19.0
    vitest: ^4.0.18

onlyBuiltDependencies:
  - esbuild
